version: '3.8'

services:
  # Bagian Backend (FastAPI)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=-1
      - TF_CPP_MIN_LOG_LEVEL=3

  # Bagian Frontend (React)
  frontend:
    build: .
    ports:
      - "5173:5173"
    depends_on:
      - backend